version: '3.7'
services:
  web:
    build: .
    volumes:
      - ./hello_rust:/usr/src/app
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    command: [ "python", "-m", "http.server", "--directory", "./", "8080" ]


